#! /usr/bin/python3
# (c) Copyright 2019-2022, James Stevens ... see LICENSE for details
# Alternative license arrangements possible, contact me for more information
""" translate a <wallet name> into a <wallet id> """

ICANN_TLDS = {
    "aaa": True, "aarp": True, "abarth": True, "abb": True, "abbott": True,
    "abbvie": True, "abc": True, "able": True, "abogado": True,
    "abudhabi": True, "ac": True, "academy": True, "accenture": True,
    "accountant": True, "accountants": True, "aco": True,
    "actor": True, "ad": True, "adac": True, "ads": True, "adult": True,
    "ae": True, "aeg": True, "aero": True, "aetna": True, "af": True,
    "afl": True, "africa": True, "ag": True, "agakhan": True, "agency": True,
    "ai": True, "aig": True, "airbus": True, "airforce": True,
    "airtel": True, "akdn": True, "al": True, "alfaromeo": True,
    "alibaba": True, "alipay": True, "allfinanz": True, "allstate": True,
    "ally": True, "alsace": True, "alstom": True, "am": True,
    "amazon": True, "americanexpress": True, "americanfamily": True,
    "amex": True, "amfam": True, "amica": True, "amsterdam": True,
    "analytics": True, "android": True, "anquan": True, "anz": True,
    "ao": True, "aol": True, "apartments": True, "app": True, "apple": True,
    "aq": True, "aquarelle": True, "ar": True, "arab": True,
    "aramco": True, "archi": True, "army": True, "arpa": True,
    "art": True, "arte": True, "as": True, "asda": True, "asia": True,
    "associates": True, "at": True, "athleta": True, "attorney": True,
    "au": True, "auction": True, "audi": True, "audible": True,
    "audio": True, "auspost": True, "author": True, "auto": True,
    "autos": True, "avianca": True, "aw": True, "aws": True, "ax": True,
    "axa": True, "az": True, "azure": True, "ba": True, "baby": True,
    "baidu": True, "banamex": True, "bananarepublic": True, "band": True,
    "bank": True, "bar": True, "barcelona": True, "barclaycard": True,
    "barclays": True, "barefoot": True, "bargains": True,
    "baseball": True, "basketball": True, "bauhaus": True,
    "bayern": True, "bb": True, "bbc": True, "bbt": True, "bbva": True,
    "bcg": True, "bcn": True, "bd": True, "be": True, "beats": True,
    "beauty": True, "beer": True, "bentley": True, "berlin": True,
    "best": True, "bestbuy": True, "bet": True, "bf": True,
    "bg": True, "bh": True, "bharti": True, "bi": True, "bible": True,
    "bid": True, "bike": True, "bing": True, "bingo": True, "bio": True,
    "biz": True, "bj": True, "black": True, "blackfriday": True,
    "blockbuster": True, "blog": True, "bloomberg": True,
    "blue": True, "bm": True, "bms": True, "bmw": True, "bn": True,
    "bnpparibas": True, "bo": True, "boats": True, "boehringer": True,
    "bofa": True, "bom": True, "bond": True, "boo": True,
    "book": True, "booking": True, "bosch": True, "bostik": True,
    "boston": True, "bot": True, "boutique": True, "box": True,
    "br": True, "bradesco": True, "bridgestone": True, "broadway": True,
    "broker": True, "brother": True, "brussels": True, "bs": True,
    "bt": True, "budapest": True, "bugatti": True, "build": True,
    "builders": True, "business": True, "buy": True, "buzz": True,
    "bv": True, "bw": True, "by": True, "bz": True, "bzh": True,
    "ca": True, "cab": True, "cafe": True, "cal": True, "call": True,
    "calvinklein": True, "cam": True, "camera": True, "camp": True,
    "cancerresearch": True, "canon": True, "capetown": True, "capital": True,
    "capitalone": True, "car": True, "caravan": True, "cards": True,
    "care": True, "career": True, "careers": True, "cars": True,
    "casa": True, "case": True, "cash": True, "casino": True,
    "cat": True, "catering": True, "catholic": True, "cba": True,
    "cbn": True, "cbre": True, "cbs": True, "cc": True, "cd": True,
    "center": True, "ceo": True, "cern": True, "cf": True, "cfa": True,
    "cfd": True, "cg": True, "ch": True, "chanel": True, "channel": True,
    "charity": True, "chase": True, "chat": True, "cheap": True,
    "chintai": True, "christmas": True, "chrome": True, "church": True,
    "ci": True, "cipriani": True, "circle": True, "cisco": True,
    "citadel": True, "citi": True, "citic": True, "city": True,
    "cityeats": True, "ck": True, "cl": True, "claims": True,
    "cleaning": True, "click": True, "clinic": True, "clinique": True,
    "clothing": True, "cloud": True, "club": True, "clubmed": True,
    "cm": True, "cn": True, "co": True, "coach": True, "codes": True,
    "coffee": True, "college": True, "cologne": True, "com": True,
    "comcast": True, "commbank": True, "community": True, "company": True,
    "compare": True, "computer": True, "comsec": True, "condos": True,
    "construction": True, "consulting": True, "contact": True,
    "contractors": True, "cooking": True, "cookingchannel": True,
    "cool": True, "coop": True, "corsica": True, "country": True,
    "coupon": True, "coupons": True, "courses": True, "cpa": True,
    "cr": True, "credit": True, "creditcard": True, "creditunion": True,
    "cricket": True, "crown": True, "crs": True, "cruise": True,
    "cruises": True, "cu": True, "cuisinella": True, "cv": True,
    "cw": True, "cx": True, "cy": True, "cymru": True, "cyou": True,
    "cz": True, "dabur": True, "dad": True, "dance": True, "data": True,
    "date": True, "dating": True, "datsun": True, "day": True,
    "dclk": True, "dds": True, "de": True, "deal": True, "dealer": True,
    "deals": True, "degree": True, "delivery": True, "dell": True,
    "deloitte": True, "delta": True, "democrat": True, "dental": True,
    "dentist": True, "desi": True, "design": True, "dev": True,
    "dhl": True, "diamonds": True, "diet": True, "digital": True,
    "direct": True, "directory": True, "discount": True, "discover": True,
    "dish": True, "diy": True, "dj": True, "dk": True, "dm": True,
    "dnp": True, "do": True, "docs": True, "doctor": True, "dog": True,
    "domains": True, "dot": True, "download": True, "drive": True,
    "dtv": True, "dubai": True, "dunlop": True, "dupont": True,
    "durban": True, "dvag": True, "dvr": True, "dz": True, "earth": True,
    "eat": True, "ec": True, "eco": True, "edeka": True, "edu": True,
    "education": True, "ee": True, "eg": True, "email": True, "emerck": True,
    "energy": True, "engineer": True, "engineering": True, "enterprises": True,
    "epson": True, "equipment": True, "er": True, "ericsson": True,
    "erni": True, "es": True, "esq": True, "estate": True,
    "et": True, "etisalat": True, "eu": True, "eurovision": True,
    "eus": True, "events": True, "exchange": True, "expert": True,
    "exposed": True, "express": True, "extraspace": True, "fage": True,
    "fail": True, "fairwinds": True, "faith": True, "family": True,
    "fan": True, "fans": True, "farm": True, "farmers": True,
    "fashion": True, "fast": True, "fedex": True, "feedback": True,
    "ferrari": True, "ferrero": True, "fi": True, "fiat": True,
    "fidelity": True, "fido": True, "film": True, "final": True,
    "finance": True, "financial": True, "fire": True, "firestone": True,
    "firmdale": True, "fish": True, "fishing": True, "fit": True,
    "fitness": True, "fj": True, "fk": True, "flickr": True, "flights": True,
    "flir": True, "florist": True, "flowers": True, "fly": True,
    "fm": True, "fo": True, "foo": True, "food": True, "foodnetwork": True,
    "football": True, "ford": True, "forex": True, "forsale": True,
    "forum": True, "foundation": True, "fox": True, "fr": True,
    "free": True, "fresenius": True, "frl": True, "frogans": True,
    "frontdoor": True, "frontier": True, "ftr": True, "fujitsu": True,
    "fun": True, "fund": True, "furniture": True, "futbol": True,
    "fyi": True, "ga": True, "gal": True, "gallery": True, "gallo": True,
    "gallup": True, "game": True, "games": True, "gap": True,
    "garden": True, "gay": True, "gb": True, "gbiz": True, "gd": True,
    "gdn": True, "ge": True, "gea": True, "gent": True, "genting": True,
    "george": True, "gf": True, "gg": True, "ggee": True, "gh": True,
    "gi": True, "gift": True, "gifts": True, "gives": True, "giving": True,
    "gl": True, "glass": True, "gle": True, "global": True,
    "globo": True, "gm": True, "gmail": True, "gmbh": True,
    "gmo": True, "gmx": True, "gn": True, "godaddy": True, "gold": True,
    "goldpoint": True, "golf": True, "goo": True, "goodyear": True,
    "goog": True, "google": True, "gop": True, "got": True,
    "gov": True, "gp": True, "gq": True, "gr": True, "grainger": True,
    "graphics": True, "gratis": True, "green": True, "gripe": True,
    "grocery": True, "group": True, "gs": True, "gt": True, "gu": True,
    "guardian": True, "gucci": True, "guge": True, "guide": True,
    "guitars": True, "guru": True, "gw": True, "gy": True, "hair": True,
    "hamburg": True, "hangout": True, "haus": True, "hbo": True,
    "hdfc": True, "hdfcbank": True, "health": True, "healthcare": True,
    "help": True, "helsinki": True, "here": True, "hermes": True,
    "hgtv": True, "hiphop": True, "hisamitsu": True, "hitachi": True,
    "hiv": True, "hk": True, "hkt": True, "hm": True, "hn": True,
    "hockey": True, "holdings": True, "holiday": True, "homedepot": True,
    "homegoods": True, "homes": True, "homesense": True,
    "honda": True, "horse": True, "hospital": True, "host": True,
    "hosting": True, "hot": True, "hoteles": True, "hotels": True,
    "hotmail": True, "house": True, "how": True, "hr": True,
    "hsbc": True, "ht": True, "hu": True, "hughes": True, "hyatt": True,
    "hyundai": True, "ibm": True, "icbc": True, "ice": True,
    "icu": True, "id": True, "ie": True, "ieee": True, "ifm": True,
    "ikano": True, "il": True, "im": True, "imamat": True, "imdb": True,
    "immo": True, "immobilien": True, "in": True, "inc": True,
    "industries": True, "infiniti": True, "info": True, "ing": True,
    "ink": True, "institute": True, "insurance": True, "insure": True,
    "int": True, "international": True, "intuit": True, "investments": True,
    "io": True, "ipiranga": True, "iq": True, "ir": True,
    "irish": True, "is": True, "ismaili": True, "ist": True, "istanbul": True,
    "it": True, "itau": True, "itv": True, "jaguar": True,
    "java": True, "jcb": True, "je": True, "jeep": True, "jetzt": True,
    "jewelry": True, "jio": True, "jll": True, "jm": True, "jmp": True,
    "jnj": True, "jo": True, "jobs": True, "joburg": True, "jot": True,
    "joy": True, "jp": True, "jpmorgan": True, "jprs": True, "juegos": True,
    "juniper": True, "kaufen": True, "kddi": True, "ke": True,
    "kerryhotels": True, "kerrylogistics": True, "kerryproperties": True,
    "kfh": True, "kg": True, "kh": True, "ki": True,
    "kia": True, "kim": True, "kinder": True, "kindle": True, "kitchen": True,
    "kiwi": True, "km": True, "kn": True, "koeln": True, "komatsu": True,
    "kosher": True, "kp": True, "kpmg": True, "kpn": True,
    "kr": True, "krd": True, "kred": True, "kuokgroup": True, "kw": True,
    "ky": True, "kyoto": True, "kz": True, "la": True, "lacaixa": True,
    "lamborghini": True, "lamer": True, "lancaster": True,
    "lancia": True, "land": True, "landrover": True, "lanxess": True,
    "lasalle": True, "lat": True, "latino": True, "latrobe": True,
    "law": True, "lawyer": True, "lb": True, "lc": True, "lds": True,
    "lease": True, "leclerc": True, "lefrak": True, "legal": True,
    "lego": True, "lexus": True, "lgbt": True, "li": True, "lidl": True,
    "life": True, "lifeinsurance": True, "lifestyle": True, "lighting": True,
    "like": True, "lilly": True, "limited": True, "limo": True,
    "lincoln": True, "linde": True, "link": True, "lipsy": True,
    "live": True, "living": True, "lk": True, "llc": True, "llp": True,
    "loan": True, "loans": True, "locker": True, "locus": True,
    "loft": True, "lol": True, "london": True, "lotte": True,
    "lotto": True, "love": True, "lpl": True, "lplfinancial": True,
    "lr": True, "ls": True, "lt": True, "ltd": True, "ltda": True,
    "lu": True, "lundbeck": True, "luxe": True, "luxury": True,
    "lv": True, "ly": True, "ma": True, "macys": True, "madrid": True,
    "maif": True, "maison": True, "makeup": True, "man": True,
    "management": True, "mango": True, "map": True, "market": True,
    "marketing": True, "markets": True, "marriott": True, "marshalls": True,
    "maserati": True, "mattel": True, "mba": True, "mc": True,
    "mckinsey": True, "md": True, "me": True, "med": True, "media": True,
    "meet": True, "melbourne": True, "meme": True, "memorial": True,
    "men": True, "menu": True, "merckmsd": True, "mg": True,
    "mh": True, "miami": True, "microsoft": True, "mil": True, "mini": True,
    "mint": True, "mit": True, "mitsubishi": True, "mk": True,
    "ml": True, "mlb": True, "mls": True, "mm": True, "mma": True,
    "mn": True, "mo": True, "mobi": True, "mobile": True, "moda": True,
    "moe": True, "moi": True, "mom": True, "monash": True, "money": True,
    "monster": True, "mormon": True, "mortgage": True, "moscow": True,
    "moto": True, "motorcycles": True, "mov": True, "movie": True,
    "mp": True, "mq": True, "mr": True, "ms": True, "msd": True,
    "mt": True, "mtn": True, "mtr": True, "mu": True, "museum": True,
    "music": True, "mutual": True, "mv": True, "mw": True, "mx": True,
    "my": True, "mz": True, "na": True, "nab": True, "nagoya": True,
    "name": True, "natura": True, "navy": True, "nba": True,
    "nc": True, "ne": True, "nec": True, "net": True, "netbank": True,
    "netflix": True, "network": True, "neustar": True, "new": True,
    "news": True, "next": True, "nextdirect": True, "nexus": True,
    "nf": True, "nfl": True, "ng": True, "ngo": True, "nhk": True,
    "ni": True, "nico": True, "nike": True, "nikon": True, "ninja": True,
    "nissan": True, "nissay": True, "nl": True, "no": True, "nokia": True,
    "northwesternmutual": True, "norton": True, "now": True,
    "nowruz": True, "nowtv": True, "np": True, "nr": True, "nra": True,
    "nrw": True, "ntt": True, "nu": True, "nyc": True, "nz": True,
    "obi": True, "observer": True, "office": True, "okinawa": True,
    "olayan": True, "olayangroup": True, "oldnavy": True, "ollo": True,
    "om": True, "omega": True, "one": True, "ong": True, "onl": True,
    "online": True, "ooo": True, "open": True, "oracle": True,
    "orange": True, "org": True, "organic": True, "origins": True,
    "osaka": True, "otsuka": True, "ott": True, "ovh": True,
    "pa": True, "page": True, "panasonic": True, "paris": True,
    "pars": True, "partners": True, "parts": True, "party": True,
    "passagens": True, "pay": True, "pccw": True, "pe": True,
    "pet": True, "pf": True, "pfizer": True, "pg": True, "ph": True,
    "pharmacy": True, "phd": True, "philips": True, "phone": True,
    "photo": True, "photography": True, "photos": True, "physio": True,
    "pics": True, "pictet": True, "pictures": True, "pid": True,
    "pin": True, "ping": True, "pink": True, "pioneer": True, "pizza": True,
    "pk": True, "pl": True, "place": True, "play": True, "playstation": True,
    "plumbing": True, "plus": True, "pm": True, "pn": True,
    "pnc": True, "pohl": True, "poker": True, "politie": True, "porn": True,
    "post": True, "pr": True, "pramerica": True, "praxi": True,
    "press": True, "prime": True, "pro": True, "prod": True,
    "productions": True, "prof": True, "progressive": True, "promo": True,
    "properties": True, "property": True, "protection": True,
    "pru": True, "prudential": True, "ps": True, "pt": True,
    "pub": True, "pw": True, "pwc": True, "py": True, "qa": True,
    "qpon": True, "quebec": True, "quest": True, "racing": True,
    "radio": True, "re": True, "read": True, "realestate": True,
    "realtor": True, "realty": True, "recipes": True, "red": True,
    "redstone": True, "redumbrella": True, "rehab": True, "reise": True,
    "reisen": True, "reit": True, "reliance": True, "ren": True,
    "rent": True, "rentals": True, "repair": True, "report": True,
    "republican": True, "rest": True, "restaurant": True, "review": True,
    "reviews": True, "rexroth": True, "rich": True, "richardli": True,
    "ricoh": True, "ril": True, "rio": True, "rip": True,
    "ro": True, "rocher": True, "rocks": True, "rodeo": True, "rogers": True,
    "room": True, "rs": True, "rsvp": True, "ru": True, "rugby": True,
    "ruhr": True, "run": True, "rw": True, "rwe": True, "ryukyu": True,
    "sa": True, "saarland": True, "safe": True, "safety": True,
    "sakura": True, "sale": True, "salon": True, "samsclub": True,
    "samsung": True, "sandvik": True, "sandvikcoromant": True,
    "sanofi": True, "sap": True, "sarl": True, "sas": True,
    "save": True, "saxo": True, "sb": True, "sbi": True, "sbs": True,
    "sc": True, "sca": True, "scb": True, "schaeffler": True, "schmidt": True,
    "scholarships": True, "school": True, "schule": True, "schwarz": True,
    "science": True, "scot": True, "sd": True, "se": True,
    "search": True, "seat": True, "secure": True, "security": True,
    "seek": True, "select": True, "sener": True, "services": True,
    "ses": True, "seven": True, "sew": True, "sex": True,
    "sexy": True, "sfr": True, "sg": True, "sh": True, "shangrila": True,
    "sharp": True, "shaw": True, "shell": True, "shia": True,
    "shiksha": True, "shoes": True, "shop": True, "shopping": True,
    "shouji": True, "show": True, "showtime": True, "si": True,
    "silk": True, "sina": True, "singles": True, "site": True, "sj": True,
    "sk": True, "ski": True, "skin": True, "sky": True, "skype": True,
    "sl": True, "sling": True, "sm": True, "smart": True, "smile": True,
    "sn": True, "sncf": True, "so": True, "soccer": True, "social": True,
    "softbank": True, "software": True, "sohu": True, "solar": True,
    "solutions": True, "song": True, "sony": True, "soy": True,
    "spa": True, "space": True, "sport": True, "spot": True, "sr": True,
    "srl": True, "ss": True, "st": True, "stada": True, "staples": True,
    "star": True, "statebank": True, "statefarm": True, "stc": True,
    "stcgroup": True, "stockholm": True, "storage": True, "store": True,
    "stream": True, "studio": True, "study": True, "style": True,
    "su": True, "sucks": True, "supplies": True, "supply": True,
    "support": True, "surf": True, "surgery": True, "suzuki": True,
    "sv": True, "swatch": True, "swiss": True, "sx": True, "sy": True,
    "sydney": True, "systems": True, "sz": True, "tab": True, "taipei": True,
    "talk": True, "taobao": True, "target": True, "tatamotors": True,
    "tatar": True, "tattoo": True, "tax": True, "taxi": True,
    "tc": True, "tci": True, "td": True, "tdk": True, "team": True,
    "tech": True, "technology": True, "tel": True, "temasek": True,
    "tennis": True, "teva": True, "tf": True, "tg": True, "th": True,
    "thd": True, "theater": True, "theatre": True, "tiaa": True,
    "tickets": True, "tienda": True, "tiffany": True, "tips": True,
    "tires": True, "tirol": True, "tj": True, "tjmaxx": True,
    "tjx": True, "tk": True, "tkmaxx": True, "tl": True, "tm": True,
    "tmall": True, "tn": True, "to": True, "today": True, "tokyo": True,
    "tools": True, "top": True, "toray": True, "toshiba": True,
    "total": True, "tours": True, "town": True, "toyota": True,
    "toys": True, "tr": True, "trade": True, "trading": True,
    "training": True, "travel": True, "travelchannel": True,
    "travelers": True, "travelersinsurance": True, "trust": True,
    "trv": True, "tt": True, "tube": True, "tui": True, "tunes": True,
    "tushu": True, "tv": True, "tvs": True, "tw": True, "tz": True,
    "ua": True, "ubank": True, "ubs": True, "ug": True, "uk": True,
    "unicom": True, "university": True, "uno": True, "uol": True,
    "ups": True, "us": True, "uy": True, "uz": True, "va": True,
    "vacations": True, "vana": True, "vanguard": True, "vc": True,
    "ve": True, "vegas": True, "ventures": True, "verisign": True,
    "versicherung": True, "vet": True, "vg": True, "vi": True,
    "viajes": True, "video": True, "vig": True, "viking": True,
    "villas": True, "vin": True, "vip": True, "virgin": True,
    "visa": True, "vision": True, "viva": True, "vivo": True,
    "vlaanderen": True, "vn": True, "vodka": True, "volkswagen": True,
    "volvo": True, "vote": True, "voting": True, "voto": True,
    "voyage": True, "vu": True, "vuelos": True, "wales": True,
    "walmart": True, "walter": True, "wang": True, "wanggou": True,
    "watch": True, "watches": True, "weather": True, "weatherchannel": True,
    "webcam": True, "weber": True, "website": True,
    "wed": True, "wedding": True, "weibo": True, "weir": True, "wf": True,
    "whoswho": True, "wien": True, "wiki": True, "williamhill": True,
    "win": True, "windows": True, "wine": True, "winners": True,
    "wme": True, "wolterskluwer": True, "woodside": True, "work": True,
    "works": True, "world": True, "wow": True, "ws": True, "wtc": True,
    "wtf": True, "xbox": True, "xerox": True, "xfinity": True,
    "xihuan": True, "xin": True, "xn--11b4c3d": True, "xn--1ck2e1b": True,
    "xn--1qqw23a": True, "xn--2scrj9c": True, "xn--30rr7y": True,
    "xn--3bst00m": True, "xn--3ds443g": True, "xn--3e0b707e": True,
    "xn--3hcrj9c": True, "xn--3pxu8k": True, "xn--42c2d9a": True,
    "xn--45br5cyl": True, "xn--45brj9c": True, "xn--45q11c": True,
    "xn--4dbrk0ce": True, "xn--4gbrim": True, "xn--54b7fta0cc": True,
    "xn--55qw42g": True, "xn--55qx5d": True, "xn--5su34j936bgsg": True,
    "xn--5tzm5g": True, "xn--6frz82g": True, "xn--6qq986b3xl": True,
    "xn--80adxhks": True, "xn--80ao21a": True, "xn--80aqecdr1a": True,
    "xn--80asehdb": True, "xn--80aswg": True, "xn--8y0a063a": True,
    "xn--90a3ac": True, "xn--90ae": True, "xn--90ais": True,
    "xn--9dbq2a": True, "xn--9et52u": True, "xn--9krt00a": True,
    "xn--b4w605ferd": True, "xn--bck1b9a5dre4c": True,
    "xn--c1avg": True, "xn--c2br7g": True, "xn--cck2b3b": True,
    "xn--cckwcxetd": True, "xn--cg4bki": True, "xn--clchc0ea0b2g2a9gcd": True,
    "xn--czr694b": True, "xn--czrs0t": True,
    "xn--czru2d": True, "xn--d1acj3b": True, "xn--d1alf": True,
    "xn--e1a4c": True, "xn--eckvdtc9d": True, "xn--efvy88h": True,
    "xn--fct429k": True, "xn--fhbei": True, "xn--fiq228c5hs": True,
    "xn--fiq64b": True, "xn--fiqs8s": True, "xn--fiqz9s": True,
    "xn--fjq720a": True, "xn--flw351e": True, "xn--fpcrj9c3d": True,
    "xn--fzc2c9e2c": True, "xn--fzys8d69uvgm": True,
    "xn--g2xx48c": True, "xn--gckr3f0f": True, "xn--gecrj9c": True,
    "xn--gk3at1e": True, "xn--h2breg3eve": True, "xn--h2brj9c": True,
    "xn--h2brj9c8c": True, "xn--hxt814e": True, "xn--i1b6b1a6a2e": True,
    "xn--imr513n": True, "xn--io0a7i": True, "xn--j1aef": True,
    "xn--j1amh": True, "xn--j6w193g": True, "xn--jlq480n2rg": True,
    "xn--jlq61u9w7b": True, "xn--jvr189m": True, "xn--kcrx77d1x4a": True,
    "xn--kprw13d": True, "xn--kpry57d": True, "xn--kput3i": True,
    "xn--l1acc": True, "xn--lgbbat1ad8j": True, "xn--mgb9awbf": True,
    "xn--mgba3a3ejt": True, "xn--mgba3a4f16a": True, "xn--mgba7c0bbn0a": True,
    "xn--mgbaakc7dvf": True, "xn--mgbaam7a8h": True,
    "xn--mgbab2bd": True, "xn--mgbah1a3hjkrd": True,
    "xn--mgbai9azgqp6j": True, "xn--mgbayh7gpa": True,
    "xn--mgbbh1a": True, "xn--mgbbh1a71e": True, "xn--mgbc0a9azcg": True,
    "xn--mgbca7dzdo": True, "xn--mgbcpq6gpa1a": True,
    "xn--mgberp4a5d4ar": True, "xn--mgbgu82a": True,
    "xn--mgbi4ecexp": True, "xn--mgbpl2fh": True, "xn--mgbt3dhd": True,
    "xn--mgbtx2b": True, "xn--mgbx4cd0ab": True, "xn--mix891f": True,
    "xn--mk1bu44c": True, "xn--mxtq1m": True, "xn--ngbc5azd": True,
    "xn--ngbe9e0a": True, "xn--ngbrx": True, "xn--node": True,
    "xn--nqv7f": True, "xn--nqv7fs00ema": True, "xn--nyqy26a": True,
    "xn--o3cw4h": True, "xn--ogbpf8fl": True, "xn--otu796d": True,
    "xn--p1acf": True, "xn--p1ai": True, "xn--pgbs0dh": True,
    "xn--pssy2u": True, "xn--q7ce6a": True, "xn--q9jyb4c": True,
    "xn--qcka1pmc": True, "xn--qxa6a": True, "xn--qxam": True,
    "xn--rhqv96g": True, "xn--rovu88b": True, "xn--rvc1e0am3e": True,
    "xn--s9brj9c": True, "xn--ses554g": True, "xn--t60b56a": True,
    "xn--tckwe": True, "xn--tiq49xqyj": True, "xn--unup4y": True,
    "xn--vermgensberater-ctb": True, "xn--vermgensberatung-pwb": True,
    "xn--vhquv": True, "xn--vuq861b": True,
    "xn--w4r85el8fhu5dnra": True, "xn--w4rs40l": True,
    "xn--wgbh1c": True, "xn--wgbl6a": True, "xn--xhq521b": True,
    "xn--xkc2al3hye2a": True, "xn--xkc2dl3a5ee0h": True,
    "xn--y9a3aq": True, "xn--yfro4i67o": True, "xn--ygbi2ammx": True,
    "xn--zfr164b": True, "xxx": True, "xyz": True, "yachts": True,
    "yahoo": True, "yamaxun": True, "yandex": True, "ye": True,
    "yodobashi": True, "yoga": True, "yokohama": True, "you": True,
    "youtube": True, "yt": True, "yun": True, "za": True, "zappos": True,
    "zara": True, "zero": True, "zip": True, "zm": True, "zone": True,
    "zuerich": True, "zw": True}
